# docker-compose.yml
version: "3"
services:
  app:
    environment:
      DATABASE_URL: postgres://dchwlewdvgkktm:66d4ee32dad329a3a9a2e06475aefbe6b710fedeb77941adb22178d8f0d1f624@ec2-54-195-247-108.eu-west-1.compute.amazonaws.com:5432/dqje0d85rpgdr
      NODE_ENV: production
